# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  
  jiraConnector:
    
    # Url to jira server
    Url: ""
    
    # Username to connect to the Jira server
    Username: ""
    
    # Password to connect to the Jira server
    # [password]
    Password: ""
