name: CI-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -DjiraConnector.url="${{secrets.URL}}" -DjiraConnector.username="${{secrets.USERNAME}}" -DjiraConnector.password="${{secrets.PASSWORD}}"
